// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Extras__Cmp from "../src/Extras__Cmp.mjs";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Primitive_int from "rescript/lib/es6/Primitive_int.js";
import * as Primitive_float from "rescript/lib/es6/Primitive_float.js";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";

function inOrder(cmp, a, b) {
  if (cmp(a, b) === -1.0) {
    return cmp(b, a) === 1.0;
  } else {
    return false;
  }
}

function isEqual(cmp, a, b) {
  if (cmp(a, b) === 0.0) {
    return cmp(b, a) === 0.0;
  } else {
    return false;
  }
}

function lessThanTests(small, big, cmp) {
  let make = (title, isTrue) => Extras__Test.fromPredicate("Cmp", title, "when different", () => isTrue);
  return [
    make("lt", Extras__Cmp.lt(cmp, small, big)),
    make("lte", Extras__Cmp.lte(cmp, small, big)),
    make("gt", Extras__Cmp.gt(cmp, big, small)),
    make("gte", Extras__Cmp.gte(cmp, big, small)),
    make("neq", Extras__Cmp.neq(cmp, big, small)),
    make("eq", Extras__Cmp.eq(cmp, big, small) === false),
    make("min", Primitive_object.equal(Extras__Cmp.min(cmp, big, small), small)),
    make("max", Primitive_object.equal(Extras__Cmp.max(cmp, big, small), big))
  ];
}

function areSameTests(a, b, cmp) {
  let make = (title, isTrue) => Extras__Test.fromPredicate("Cmp", title, "when same", () => isTrue);
  return [
    make("lt", false === Extras__Cmp.lt(cmp, a, b)),
    make("lte", Extras__Cmp.lte(cmp, a, b)),
    make("gt", false === Extras__Cmp.gt(cmp, a, b)),
    make("gte", Extras__Cmp.gte(cmp, a, b)),
    make("neq", false === Extras__Cmp.neq(cmp, a, b)),
    make("eq", Extras__Cmp.eq(cmp, a, b)),
    make("min", Primitive_object.equal(Extras__Cmp.min(cmp, a, b), a)),
    make("max", Primitive_object.equal(Extras__Cmp.max(cmp, a, b), a))
  ];
}

let otherTests = [
  Extras__Test.fromPredicate("Cmp", "fromMap", undefined, () => {
    let target = (extra, extra$1) => Extras__Cmp.fromMap(i => i.age, Primitive_int.compare, extra, extra$1);
    return inOrder(target, {
      name: "bob",
      age: 3
    }, {
      name: "sue",
      age: 8
    });
  }),
  Extras__Test.fromPredicate("Cmp", "fromIntResult", undefined, () => {
    let f = (x, y) => {
      if (x < y) {
        return -1;
      } else if (x > y) {
        return 1;
      } else {
        return 0;
      }
    };
    let target = (extra, extra$1) => Extras__Cmp.fromIntResult(f, extra, extra$1);
    if (inOrder(target, 3, 9)) {
      return isEqual(target, 3, 3);
    } else {
      return false;
    }
  }),
  Extras__Test.fromPredicate("Cmp", "int instance", undefined, () => {
    if (inOrder(Primitive_int.compare, 1, 2)) {
      return isEqual(Primitive_int.compare, 1, 1);
    } else {
      return false;
    }
  }),
  Extras__Test.fromPredicate("Cmp", "float instance", undefined, () => {
    if (inOrder(Primitive_float.compare, 1.0, 2.0)) {
      return isEqual(Primitive_float.compare, 1.0, 1.0);
    } else {
      return false;
    }
  }),
  Extras__Test.fromPredicate("Cmp", "bool instance", undefined, () => {
    if (inOrder(Extras__Cmp.bool, false, true)) {
      return isEqual(Extras__Cmp.bool, false, false);
    } else {
      return false;
    }
  })
];

let tests = [
  lessThanTests(1, 99, Primitive_int.compare),
  lessThanTests(1, 99, Primitive_int.compare),
  lessThanTests("a", "b", (prim0, prim1) => prim0.localeCompare(prim1)),
  areSameTests(1.0, 1.0, Primitive_float.compare),
  areSameTests(1, 1, Primitive_int.compare),
  areSameTests("abc", "abc", (prim0, prim1) => prim0.localeCompare(prim1)),
  otherTests
].flat();

let T;

let C;

let A;

export {
  T,
  C,
  A,
  inOrder,
  isEqual,
  lessThanTests,
  areSameTests,
  otherTests,
  tests,
}
/* otherTests Not a pure module */
