// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Option from "rescript/lib/es6/Option.js";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__Option from "../src/Extras__Option.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function expectEq(title, expectation, a, b) {
  return Extras__Test.fromPredicate("Option", title, expectation, () => Primitive_object.equal(a(), b));
}

function add(a, b) {
  return a + b | 0;
}

function add3(a, b, c) {
  return (a + b | 0) + c | 0;
}

function add4(a, b, c, d) {
  return ((a + b | 0) + c | 0) + d | 0;
}

let tests = [
  expectEq("isSomeAnd", "when None => false", () => Extras__Option.isSomeAnd(undefined, param => true), false),
  expectEq("isSomeAnd", "when Some and condition met => true", () => Extras__Option.isSomeAnd(3, i => i === 3), true),
  expectEq("isSomeAnd", "when Some and condition not met => false", () => Extras__Option.isSomeAnd(3, i => i === 9), false),
  expectEq("isNoneOr", "when None => true", () => Extras__Option.isNoneOr(undefined, param => false), true),
  expectEq("isNoneOr", "when Some and condition met => true", () => Extras__Option.isNoneOr(3, i => i === 3), true),
  expectEq("isNoneOr", "when Some and condition not met => false", () => Extras__Option.isNoneOr(3, i => i === 9999), false),
  expectEq("concat", "when both None => None", () => Extras__Option.concat(undefined, undefined, add), undefined),
  expectEq("concat", "when first is Some => Some", () => Extras__Option.concat(4, undefined, add), 4),
  expectEq("concat", "when second is Some => Some", () => Extras__Option.concat(undefined, 4, add), 4),
  expectEq("concat", "when both Some => apply concat function", () => Extras__Option.concat(3, 4, add), 7),
  expectEq("fold", "when None, return current sum", () => Extras__Option.fold(undefined, add, 4), 4),
  expectEq("fold", "when Some, fold item into sum", () => Extras__Option.fold(3, add, 4), 7),
  expectEq("foldBack", "when None, return current sum", () => Extras__Option.foldBack(4, add, undefined), 4),
  expectEq("foldBack", "when Some, fold item into sum", () => Extras__Option.foldBack(3, add, 4), 7),
  expectEq("toArray", "when None => empty", () => Extras__Option.toArray(undefined), []),
  expectEq("toArray", "when Some => array of one item", () => Extras__Option.toArray(4), [4]),
  expectEq("fromOk", "when Ok => Some", () => Extras__Option.fromOk({
    TAG: "Ok",
    _0: 5
  }), 5),
  expectEq("fromOk", "when Error => None", () => Extras__Option.fromOk({
    TAG: "Error",
    _0: 5
  }), undefined),
  expectEq("fromError", "when Error => Some", () => Extras__Option.fromError({
    TAG: "Error",
    _0: 5
  }), 5),
  expectEq("fromError", "when Ok => None", () => Extras__Option.fromError({
    TAG: "Ok",
    _0: 5
  }), undefined),
  Extras__Test.fromPredicate("Option", "fromTryCatch", "when throw, return as None", () => Option.isNone(Extras__Option.fromTryCatch(() => Exn.raiseError("banana")))),
  Extras__Test.fromPredicate("Option", "fromTryCatch", "when not throw, return result as Some", () => Primitive_object.equal(Extras__Option.fromTryCatch(() => 3), 3)),
  expectEq("map2", "when 0/2 Some => None", () => Extras__Option.map2(undefined, undefined, add), undefined),
  expectEq("map2", "when 2/2 Some => Some with map args", () => Extras__Option.map2(1, 5, add), 6),
  expectEq("map2", "when 1/2 is Some => None", () => Extras__Option.map2(1, undefined, add), undefined),
  expectEq("map2", "when 1/2 is Some => None", () => Extras__Option.map2(undefined, 1, add), undefined),
  expectEq("map3", "when 3/3 is Some => Some with map args", () => Extras__Option.map3(1, 5, 9, add3), 15),
  expectEq("map3", "when 2/3 is Some => None", () => Extras__Option.map3(1, undefined, 5, add3), undefined),
  expectEq("map3", "when 1/3 is Some => None", () => Extras__Option.map3(undefined, 1, undefined, add3), undefined),
  expectEq("map3", "when 0/3 is Some => None", () => Extras__Option.map3(undefined, undefined, undefined, add3), undefined),
  expectEq("orElseWith", "when first is Some, return it", () => Extras__Option.orElseWith(1, () => 2), 1),
  expectEq("orElseWith", "when first is None, return lazy second", () => Extras__Option.orElseWith(undefined, () => 2), 2),
  expectEq("flatten", "when Some Some => Some", () => Extras__Option.flatten(4), 4),
  expectEq("flatten", "when Some None => None", () => Extras__Option.flatten(Primitive_option.some(undefined)), undefined)
];

let T;

let O;

export {
  expectEq,
  T,
  O,
  add,
  add3,
  add4,
  tests,
}
/* tests Not a pure module */
