// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Int from "rescript/lib/es6/Int.js";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__Literal from "../src/Extras__Literal.mjs";
import * as Extras__Pattern from "../src/Extras__Pattern.mjs";

function isTypeOfTest(title, guard, ok, invalid1, invalid2, invalid3) {
  return Extras__Test.fromPredicate("Patterns", title, "isTypeOf", () => {
    if (true === ok.every(i => guard(i)) && false === guard(invalid1) && false === guard(invalid2)) {
      return false === guard(invalid3);
    } else {
      return false;
    }
  });
}

function areEqual(title, equals, expectation, a, b) {
  return Extras__Test.fromPredicate("Patterns", title + " equals", expectation, () => {
    if (equals(a, b)) {
      return equals(b, a);
    } else {
      return false;
    }
  });
}

function areNotEqual(title, equals, expectation, a, b) {
  return Extras__Test.fromPredicate("Patterns", title + " equals", expectation, () => {
    if (equals(a, b)) {
      return false;
    } else {
      return !equals(b, a);
    }
  });
}

let Negative1 = Extras__Literal.MakeInt({
  value: -1
});

let Yes = Extras__Literal.MakeString({
  value: "yes",
  trimmed: true,
  caseInsensitive: true
});

let OptionString = Extras__Pattern.MakeOption(Extras__Pattern.$$String);

let NullableString = Extras__Pattern.MakeNullable(Extras__Pattern.$$String);

let NullInt = Extras__Pattern.MakeNull(Extras__Pattern.Int);

let IntStringTuple = Extras__Pattern.MakeTuple2({
  A: Extras__Pattern.Int,
  B: Extras__Pattern.$$String
});

let tests = [
  isTypeOfTest("Null (null literal)", Extras__Literal.Null.isTypeOf, [null], false, 33, "abc"),
  isTypeOfTest("True (bool literal)", Extras__Literal.True.isTypeOf, [
    true,
    Extras__Literal.True.value
  ], false, 33, "abc"),
  isTypeOfTest("Yes (string literal)", Yes.isTypeOf, [
    "yes",
    "  YES",
    "  yEs"
  ], "no", 33, false),
  isTypeOfTest("Negative1 (int literal)", Negative1.isTypeOf, [-1], 0, 3.4, "abc"),
  isTypeOfTest("Int", Extras__Pattern.Int.isTypeOf, [
    1,
    -1,
    34,
    Int.Constants.maxValue
  ], "abc", false, {
    a: 1
  }),
  isTypeOfTest("String", Extras__Pattern.$$String.isTypeOf, [
    "abc",
    "",
    "   a b c"
  ], false, 43, 4.3),
  isTypeOfTest("Bool", Extras__Pattern.Bool.isTypeOf, [
    true,
    false
  ], 43, "abc", 4.3),
  isTypeOfTest("Date", Extras__Pattern.$$Date.isTypeOf, [new Date(Date.now())], "abc", 3, new Date("abc")),
  isTypeOfTest("MakeOption (string)", OptionString.isTypeOf, [
    "abc",
    undefined,
    ""
  ], 1, false, 4.5),
  areNotEqual("MakeOption (string)", OptionString.equals, "when one undefined => false", undefined, "abc"),
  areEqual("MakeOption (string)", OptionString.equals, "when both undefined => true", undefined, undefined),
  areNotEqual("MakeOption (string)", OptionString.equals, "when both Some but values different => false", "xyz", "abc"),
  areEqual("MakeOption (string)", OptionString.equals, "when both Some but values same => true", "xyz", "xyz"),
  isTypeOfTest("MakeNullable (string)", NullableString.isTypeOf, [
    "abc",
    null,
    undefined
  ], 1, false, 4.5),
  areEqual("MakeNullable (string)", NullableString.equals, "when both undefined => true", undefined, undefined),
  areEqual("MakeNullable (string)", NullableString.equals, "when both null => true", null, null),
  areNotEqual("MakeNullable (string)", NullableString.equals, "when one undefined and other null => false", null, undefined),
  areEqual("MakeNullable (string)", NullableString.equals, "when same string => true", "abc", "abc"),
  areNotEqual("MakeNullable (string)", NullableString.equals, "when different string => false", "abc", "xyz"),
  areNotEqual("MakeNullable (string)", NullableString.equals, "when one undefined and other is string => false", "abc", undefined),
  areNotEqual("MakeNullable (string)", NullableString.equals, "when one null and other is string => false", "abc", null),
  isTypeOfTest("MakeNull (int)", NullInt.isTypeOf, [
    3,
    6,
    null
  ], "abc", false, {
    a: 1
  }),
  areEqual("MakeNull (int)", NullInt.equals, "when both null => true", null, null),
  areEqual("MakeNull (int)", NullInt.equals, "when both same non-null value => true", 3, 3),
  areNotEqual("MakeNull (int)", NullInt.equals, "when one is null => false", null, 3),
  areNotEqual("MakeNull (int)", NullInt.equals, "when both different non-null value => false", 5, 3),
  isTypeOfTest("Tuple", IntStringTuple.isTypeOf, [
    [
      1,
      "abc"
    ],
    [
      4,
      "x"
    ]
  ], "abc", false, [
    1,
    "abc",
    false
  ])
];

let Test;

let Pattern;

let Unknown;

let Literal;

export {
  Test,
  Pattern,
  Unknown,
  Literal,
  isTypeOfTest,
  areEqual,
  areNotEqual,
  Negative1,
  Yes,
  OptionString,
  NullableString,
  NullInt,
  IntStringTuple,
  tests,
}
/* Negative1 Not a pure module */
