// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__Trampoline from "../src/Extras__Trampoline.mjs";

function factorial(n) {
  let go = (total, n) => {
    if (n !== 1) {
      return Extras__Trampoline.work(() => go(Math.imul(total, n), n - 1 | 0));
    } else {
      return Extras__Trampoline.resolve(total);
    }
  };
  return Extras__Trampoline.solve(Extras__Trampoline.work(() => go(1, n)));
}

let factorialTests = [
  [
    1,
    1
  ],
  [
    2,
    2
  ],
  [
    3,
    6
  ],
  [
    4,
    24
  ],
  [
    12,
    479001600
  ]
].map(param => {
  let total = param[1];
  let n = param[0];
  return Extras__Test.fromPredicate("Functions", "Trampoline (factorial)", n.toString() + "! == " + total.toString(), () => factorial(n) === total);
});

function decrement(n) {
  let go = current => {
    if (current === 0) {
      return Extras__Trampoline.resolve(current);
    } else {
      return Extras__Trampoline.work(() => go(current - 1 | 0));
    }
  };
  return Extras__Trampoline.solve(Extras__Trampoline.work(() => go(n)));
}

let decrementTests = [
  10,
  100,
  999999
].map(n => Extras__Test.fromPredicate("Functions", "Trampoline (decrement)", "Can decrement from " + n.toString(), () => decrement(n) === 0));

let tests = [
  factorialTests,
  decrementTests
].flatMap(i => i);

let T;

let TR;

export {
  T,
  TR,
  factorial,
  factorialTests,
  decrement,
  decrementTests,
  tests,
}
/* factorialTests Not a pure module */
