// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Option from "rescript/lib/es6/Option.js";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__Union from "../src/Extras__Union.mjs";
import * as Extras__Option from "../src/Extras__Option.mjs";
import * as Extras__Literal from "../src/Extras__Literal.mjs";
import * as Extras__Pattern from "../src/Extras__Pattern.mjs";
import * as Extras__Unknown from "../src/Extras__Unknown.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as S$RescriptSchema from "rescript-schema/src/S.mjs";

let StringOrFalseBasic = Extras__Union.Make2({
  A: Extras__Pattern.$$String,
  B: {
    isTypeOf: Extras__Literal.False.isTypeOf,
    equals: Extras__Literal.False.equals
  }
});

let include = Extras__Union.Make2({
  A: Extras__Pattern.$$String,
  B: {
    isTypeOf: Extras__Literal.False.isTypeOf,
    equals: Extras__Literal.False.equals
  }
});

let toA = include.toA;

let toB = include.toB;

let make = include.make;

let matchAB = include.matchAB;

let equals = include.equals;

function fromString(prim) {
  return prim;
}

function fromFalse(prim) {
  return prim;
}

function match(value, onString, onFalse) {
  return matchAB(value, onString, onFalse);
}

let StringOrFalse = {
  toA: toA,
  toB: toB,
  make: make,
  matchAB: matchAB,
  equals: equals,
  fromString: fromString,
  fromFalse: fromFalse,
  toString: toA,
  toFalse: toB,
  match: match
};

function test(expectation, predicate) {
  return Extras__Test.fromPredicate("Union", "StringOrFalse", expectation, predicate);
}

let tests = [
  test("fromString (safe assignment)", () => equals("abc", "abc")),
  test("fromFalse (safe assignment)", () => equals(Extras__Literal.False.value, false)),
  test("make from false => Some", () => Extras__Option.isSomeAnd(make(false), v => v === false)),
  test("make from true => None", () => Option.isNone(make(true))),
  test("make from string => Some", () => Extras__Option.isSomeAnd(make("abc"), v => v === "abc")),
  test("make from int => None", () => Option.isNone(make(34))),
  test("match on string", () => matchAB("abc", i => i === "abc", param => false)),
  test("equals when both false => true", () => equals(Extras__Literal.False.value, Extras__Literal.False.value)),
  test("equals when both string and same string => true", () => equals("abc", "abc")),
  test("equals when both string but different => false", () => false === equals("abc", "xyz")),
  test("equals when one string and one false => false", () => false === equals("abc", Extras__Literal.False.value)),
  test("equals when one string and one false => false", () => false === equals("abc", Extras__Literal.False.value)),
  test("toString when string => Some", () => Primitive_object.equal(toA("abc"), "abc")),
  test("toString when not string => None", () => Option.isNone(toA(Extras__Literal.False.value))),
  test("toFalse when false => Some", () => Primitive_object.equal(toB(Extras__Literal.False.value), Primitive_option.some(Extras__Literal.False.value))),
  test("toFalse when not false => None", () => Option.isNone(toB("abc")))
];

let StringOrFalseTests = {
  StringOrFalseBasic: StringOrFalseBasic,
  StringOrFalse: StringOrFalse,
  tests: tests
};

let A = Extras__Pattern.MakeOption(Extras__Pattern.$$String);

let StringOptionOrInt = Extras__Union.Make2({
  A: A,
  B: Extras__Pattern.Int
});

let A$1 = Extras__Pattern.MakeTuple2({
  A: Extras__Pattern.$$String,
  B: Extras__Pattern.Bool
});

let TupleOrString = Extras__Union.Make2({
  A: A$1,
  B: Extras__Pattern.Int
});

function isTypeOf(u) {
  return Extras__Option.isSomeAnd(Extras__Unknown.getBool(u, "success"), v => v === true);
}

function equals$1(x, y) {
  return x.count === y.count;
}

let Success = {
  isTypeOf: isTypeOf,
  equals: equals$1
};

function isTypeOf$1(u) {
  return Extras__Option.isSomeAnd(Extras__Unknown.getBool(u, "success"), v => v === false);
}

function equals$2(x, y) {
  return x.reason === y.reason;
}

let Failure = {
  isTypeOf: isTypeOf$1,
  equals: equals$2
};

let NegativeOne = Extras__Literal.MakeInt({
  value: -1
});

let include$1 = Extras__Union.Make4({
  A: Success,
  B: Failure,
  C: {
    isTypeOf: Extras__Literal.Null.isTypeOf,
    equals: Extras__Literal.Null.equals
  },
  D: {
    isTypeOf: NegativeOne.isTypeOf,
    equals: NegativeOne.equals
  }
});

let toA$1 = include$1.toA;

let toB$1 = include$1.toB;

let toC = include$1.toC;

let toD = include$1.toD;

let make$1 = include$1.make;

let matchABCD = include$1.matchABCD;

function fromSuccess(prim) {
  return prim;
}

function fromFailure(prim) {
  return prim;
}

function fromNull(prim) {
  return prim;
}

function fromNegativeOne(prim) {
  return prim;
}

function match$1(value, onSuccess, onFailure, onNull, onNegativeOne) {
  return matchABCD(value, onSuccess, onFailure, onNull, onNegativeOne);
}

let Target_equals = include$1.equals;

let Target = {
  toA: toA$1,
  toB: toB$1,
  toC: toC,
  toD: toD,
  make: make$1,
  matchABCD: matchABCD,
  equals: Target_equals,
  fromSuccess: fromSuccess,
  fromFailure: fromFailure,
  fromNull: fromNull,
  fromNegativeOne: fromNegativeOne,
  toSuccess: toA$1,
  toFailure: toB$1,
  toNull: toC,
  toNegativeOne: toD,
  match: match$1
};

function test$1(expectation, predicate) {
  return Extras__Test.fromPredicate("Union", "Fancy", expectation, predicate);
}

let tests$1 = [
  test$1("fromNegativeOne", () => NegativeOne.value === -1),
  test$1("fromNull", () => Extras__Literal.Null.value === null),
  test$1("fromSuccess", () => {
    let value = {
      success: Extras__Literal.True.value,
      count: 5
    };
    return Primitive_object.equal(value, value);
  }),
  test$1("make from NegativeOne => Some", () => Primitive_object.equal(make$1(NegativeOne.value), -1)),
  test$1("make from invalid value like 34 => None", () => Option.isNone(make$1(34))),
  test$1("match on Success", () => match$1(Option.getExn(make$1({
    success: Extras__Literal.True.value,
    count: 5
  }), undefined), i => i.count === 5, param => false, param => false, param => false)),
  test$1("match on NegativeOne", () => match$1(Option.getExn(make$1(-1), undefined), param => false, param => false, param => false, param => true)),
  test$1("toNull when null => Some", () => Option.isSome(toC(Extras__Literal.Null.value))),
  test$1("toNull when something else => None", () => Option.isNone(toC(NegativeOne.value))),
  test$1("match on Null", () => match$1(Extras__Literal.Null.value, param => false, param => false, param => true, param => false))
];

let FancyUnionTest = {
  Success: Success,
  Failure: Failure,
  NegativeOne: NegativeOne,
  Target: Target,
  tests: tests$1
};

function isTypeOf$2(u) {
  if (Array.isArray(u)) {
    return u.length === 2;
  } else {
    return false;
  }
}

let equals$3 = Primitive_object.equal;

let Point2D = {
  isTypeOf: isTypeOf$2,
  equals: equals$3
};

function isTypeOf$3(u) {
  if (Array.isArray(u)) {
    return u.length === 3;
  } else {
    return false;
  }
}

let equals$4 = Primitive_object.equal;

let Point3D = {
  isTypeOf: isTypeOf$3,
  equals: equals$4
};

let Point = Extras__Union.Make2({
  A: Point2D,
  B: Point3D
});

function test$2(expectation, predicate) {
  return Extras__Test.fromPredicate("Union", "Point", expectation, predicate);
}

let tests$2 = [
  test$2("make from 2d => Some", () => Option.isSome(Point.make([
    1.0,
    1.0
  ]))),
  test$2("make from 3d => Some", () => Option.isSome(Point.make([
    1.0,
    1.0,
    1.0
  ]))),
  test$2("make from 4d => None", () => Option.isNone(Point.make([
    1.0,
    1.0,
    1.0,
    1.0
  ]))),
  test$2("make from empty => None", () => Option.isNone(Point.make([]))),
  test$2("make from string => None", () => Option.isNone(Point.make("abc"))),
  test$2("match on 2d", () => {
    let p = [
      1.0,
      1.0
    ];
    return Point.matchAB(p, i => i === p, param => false);
  }),
  test$2("match on 3d", () => {
    let p = [
      1.0,
      1.0,
      1.0
    ];
    return Point.matchAB(p, param => false, i => i === p);
  }),
  test$2("match on 3d", () => Point.matchAB([
    2.0,
    3.0,
    4.0
  ], param => false, param => {
    if (param[0] === 2.0 && param[1] === 3.0) {
      return param[2] === 4.0;
    } else {
      return false;
    }
  }))
];

let PointTests = {
  Point2D: Point2D,
  Point3D: Point3D,
  Point: Point,
  test: test$2,
  tests: tests$2
};

let struct = S$RescriptSchema.to(S$RescriptSchema.stringMaxLength(S$RescriptSchema.stringMinLength(S$RescriptSchema.string, 3, undefined), 10, undefined), s => s);

function make$2(s) {
  return Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(s, struct));
}

function equals$5(x, y) {
  return x === y;
}

let ShortString = {
  struct: struct,
  make: make$2,
  equals: equals$5
};

let struct$1 = S$RescriptSchema.to(S$RescriptSchema.intMin(S$RescriptSchema.int, 0, undefined), n => n);

function make$3(n) {
  return Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(n, struct$1));
}

function equals$6(x, y) {
  return x === y;
}

let NonNegativeInt = {
  struct: struct$1,
  make: make$3,
  equals: equals$6
};

let struct$2 = S$RescriptSchema.object(o => ({
  x: o.f("x", S$RescriptSchema.int),
  y: o.f("y", S$RescriptSchema.int)
}));

function make$4(x, y) {
  return {
    x: x,
    y: y
  };
}

function equals$7(a, b) {
  if (a.x === b.x) {
    return a.y === b.y;
  } else {
    return false;
  }
}

let Point$1 = {
  struct: struct$2,
  make: make$4,
  equals: equals$7
};

let unionStruct = S$RescriptSchema.union([
  struct$2,
  struct,
  struct$1
]);

function toPoint(i) {
  return Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(i, struct$2));
}

function toShortString(i) {
  return Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(i, struct));
}

function toNonNegativeInt(i) {
  return Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(i, struct$1));
}

function make$5(i) {
  return Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(i, unionStruct));
}

function match$2(value, onPoint, onInt, onString) {
  let result = Extras__Option.orElseWith(Extras__Option.orElseWith(Option.map(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(value, struct$2)), onPoint), () => Option.map(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(value, struct$1)), onInt)), () => Option.map(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(value, struct)), onString));
  if (result !== undefined) {
    return Primitive_option.valFromOption(result);
  } else {
    return Exn.raiseError("Unsafely cast value; did not pattern match.");
  }
}

function equalsBy(f, eq, x, y) {
  return Option.map(f(x), x => Option.mapOr(f(y), false, y => eq(x, y)));
}

function equals$8(x, y) {
  return Option.getOr(Extras__Option.orElseWith(Extras__Option.orElseWith(equalsBy(toPoint, equals$7, x, y), () => equalsBy(toNonNegativeInt, equals$6, x, y)), () => equalsBy(toShortString, equals$5, x, y)), false);
}

let Target$1 = {
  toPoint: toPoint,
  toNonNegativeInt: toNonNegativeInt,
  toShortString: toShortString,
  make: make$5,
  match: match$2,
  equals: equals$8
};

function test$3(expectation, predicate) {
  return Extras__Test.fromPredicate("Union", "Use RescriptSchema exclusively", expectation, predicate);
}

let tests$3 = [
  test$3("make from short string => Some", () => Extras__Option.isSomeAnd(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow("abc", unionStruct)), v => v === "abc")),
  test$3("make from long string => None", () => Option.isNone(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow("abcdefghijklmnopqrstuv", unionStruct)))),
  test$3("make from positive int => Some", () => {
    let i = Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(34, struct$1)), undefined);
    return Extras__Option.isSomeAnd(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(i, unionStruct)), i => i === 34);
  }),
  test$3("make from negative number => None", () => Option.isNone(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(-99, unionStruct)))),
  test$3("make from point => Some", () => {
    let i = {
      x: 2,
      y: 3
    };
    return Extras__Option.isSomeAnd(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(i, unionStruct)), v => equals$7(v, {
      x: 2,
      y: 3
    }));
  }),
  test$3("make from point => Some with exact same instance", () => {
    let p = {
      x: 2,
      y: 3
    };
    return p === p;
  }),
  test$3("match on point", () => {
    let i = {
      x: 2,
      y: 3
    };
    return match$2(Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(i, unionStruct)), undefined), p => {
      if (p.x === 2) {
        return p.y === 3;
      } else {
        return false;
      }
    }, param => false, param => false);
  }),
  test$3("match on positive int", () => match$2(Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(16, unionStruct)), undefined), param => false, i => i === 16, param => false)),
  test$3("equality of int", () => equals$8(Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(1, struct$1)), undefined), Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(1, struct$1)), undefined))),
  test$3("equality of int", () => false === equals$8(Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(1, struct$1)), undefined), Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(2, struct$1)), undefined))),
  test$3("equality of int and string", () => false === equals$8(Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(1, struct$1)), undefined), Option.getExn(Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow("abcde", struct)), undefined))),
  test$3("equality of point", () => equals$8({
    x: 1,
    y: 2
  }, {
    x: 1,
    y: 2
  })),
  test$3("equality of point", () => false === equals$8({
    x: 1,
    y: 2
  }, {
    x: 9,
    y: 9
  }))
];

let OnlyRescriptSchemaTests = {
  ShortString: ShortString,
  NonNegativeInt: NonNegativeInt,
  Point: Point$1,
  Target: Target$1,
  test: test$3,
  tests: tests$3
};

function exceptionNotThrown(f) {
  try {
    return true;
  } catch (exn) {
    return false;
  }
}

let struct$3 = S$RescriptSchema.to(S$RescriptSchema.stringMaxLength(S$RescriptSchema.stringMinLength(S$RescriptSchema.string, 3, undefined), 10, undefined), s => s);

function make$6(s) {
  return Extras__Option.fromTryCatch(() => S$RescriptSchema.parseOrThrow(s, struct$3));
}

function isTypeOf$4(s) {
  return exceptionNotThrown(() => S$RescriptSchema.parseOrThrow(s, struct$3));
}

function equals$9(x, y) {
  return x === y;
}

let ShortString$1 = {
  struct: struct$3,
  make: make$6,
  isTypeOf: isTypeOf$4,
  equals: equals$9
};

let struct$4 = S$RescriptSchema.to(S$RescriptSchema.intMin(S$RescriptSchema.int, 0, undefined), n => n);

function make$7(n) {
  return exceptionNotThrown(() => S$RescriptSchema.parseOrThrow(n, struct$4));
}

function isTypeOf$5(s) {
  return exceptionNotThrown(() => S$RescriptSchema.parseOrThrow(s, struct$4));
}

function equals$10(x, y) {
  return x === y;
}

let NonNegativeInt$1 = {
  struct: struct$4,
  make: make$7,
  isTypeOf: isTypeOf$5,
  equals: equals$10
};

let struct$5 = S$RescriptSchema.object(o => ({
  x: o.f("x", S$RescriptSchema.int),
  y: o.f("y", S$RescriptSchema.int)
}));

function make$8(x, y) {
  return {
    x: x,
    y: y
  };
}

function isTypeOf$6(s) {
  return exceptionNotThrown(() => S$RescriptSchema.parseOrThrow(s, struct$5));
}

function equals$11(a, b) {
  if (a.x === b.x) {
    return a.y === b.y;
  } else {
    return false;
  }
}

let Point$2 = {
  struct: struct$5,
  make: make$8,
  isTypeOf: isTypeOf$6,
  equals: equals$11
};

let include$2 = Extras__Union.Make3({
  A: {
    isTypeOf: isTypeOf$4,
    equals: equals$9
  },
  B: {
    isTypeOf: isTypeOf$5,
    equals: equals$10
  },
  C: {
    isTypeOf: isTypeOf$6,
    equals: equals$11
  }
});

let toA$2 = include$2.toA;

let toB$2 = include$2.toB;

let toC$1 = include$2.toC;

let matchABC = include$2.matchABC;

function fromString$1(prim) {
  return prim;
}

function fromNonNegativeInt(prim) {
  return prim;
}

function fromPoint(prim) {
  return prim;
}

function match$3(onString, onInt, onPoint) {
  return __x => matchABC(__x, onString, onInt, onPoint);
}

let Target_make = include$2.make;

let Target_equals$1 = include$2.equals;

let Target$2 = {
  toA: toA$2,
  toB: toB$2,
  toC: toC$1,
  make: Target_make,
  matchABC: matchABC,
  equals: Target_equals$1,
  fromString: fromString$1,
  fromNonNegativeInt: fromNonNegativeInt,
  fromPoint: fromPoint,
  toString: toA$2,
  toNonNegativeInt: toB$2,
  toPoint: toC$1,
  match: match$3
};

let WithHelpFromRescriptSchema = {
  exceptionNotThrown: exceptionNotThrown,
  ShortString: ShortString$1,
  NonNegativeInt: NonNegativeInt$1,
  Point: Point$2,
  Target: Target$2
};

function isTypeOf$7(param) {
  Exn.raiseError("Tried to parse a string.");
  return true;
}

function equals$12(a, b) {
  return a === b;
}

let StringThrows = {
  isTypeOf: isTypeOf$7,
  equals: equals$12
};

let IntOrBoolOrFloatOrString = Extras__Union.Make4({
  A: Extras__Pattern.Int,
  B: Extras__Pattern.Bool,
  C: Extras__Pattern.Float,
  D: StringThrows
});

let IntOrBoolOrString = Extras__Union.Make3({
  A: Extras__Pattern.Int,
  B: Extras__Pattern.Bool,
  C: StringThrows
});

let IntOrString = Extras__Union.Make2({
  A: Extras__Pattern.Int,
  B: StringThrows
});

function test$4(expectation, predicate) {
  return Extras__Test.fromPredicate("Union", "Lazy evaluation", expectation, predicate);
}

let tests$4 = [
  test$4("4 make from int => Some", () => Extras__Option.isSomeAnd(IntOrBoolOrFloatOrString.make(1), v => v === 1)),
  test$4("4 make from bool => Some", () => Extras__Option.isSomeAnd(IntOrBoolOrFloatOrString.make(true), v => v === true)),
  test$4("4 make from float => Some", () => Extras__Option.isSomeAnd(IntOrBoolOrFloatOrString.make(3.5), v => v === 3.5)),
  test$4("3 make from int => Some", () => Extras__Option.isSomeAnd(IntOrBoolOrString.make(1), v => v === 1)),
  test$4("3 make from bool => Some", () => Extras__Option.isSomeAnd(IntOrBoolOrString.make(true), v => v === true)),
  test$4("3 match from int", () => IntOrBoolOrString.matchABC(1, i => i === 1, param => false, param => false)),
  test$4("3 match from bool", () => IntOrBoolOrString.matchABC(true, param => false, b => b === true, param => false)),
  test$4("2 make from int => Some", () => Extras__Option.isSomeAnd(IntOrString.make(1), v => v === 1)),
  test$4("2 match from int", () => IntOrString.matchAB(1, i => i === 1, param => false))
];

let LazinessTests = {
  StringThrows: StringThrows,
  IntOrBoolOrFloatOrString: IntOrBoolOrFloatOrString,
  IntOrBoolOrString: IntOrBoolOrString,
  IntOrString: IntOrString,
  test: test$4,
  tests: tests$4
};

let tests$5 = [
  tests,
  tests$1,
  tests$2,
  tests$3,
  tests$4
].flat();

let Ex;

let Union;

let Literal;

let Unknown;

let ResultEx;

let OptionEx;

let Test;

let ArrayEx;

let Pattern;

export {
  Ex,
  Union,
  Literal,
  Unknown,
  ResultEx,
  OptionEx,
  Test,
  ArrayEx,
  Pattern,
  StringOrFalseTests,
  StringOptionOrInt,
  TupleOrString,
  FancyUnionTest,
  PointTests,
  OnlyRescriptSchemaTests,
  WithHelpFromRescriptSchema,
  LazinessTests,
  tests$5 as tests,
}
/* StringOrFalseBasic Not a pure module */
