// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Option from "rescript/lib/es6/Option.js";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Primitive_int from "rescript/lib/es6/Primitive_int.js";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Extras__NonEmptyArray from "../src/Extras__NonEmptyArray.mjs";

function expectEq(title, expectation, a, b) {
  return Extras__Test.fromPredicate("NonEmptyArray", title, expectation, () => Primitive_object.equal(a(), b));
}

function add(x, y) {
  return x + y | 0;
}

let tests = [
  expectEq("fromArray", "when empty => None", () => Extras__NonEmptyArray.fromArray([]), undefined),
  expectEq("fromArray", "when one item => Some", () => Option.map(Extras__NonEmptyArray.fromArray([1]), prim => prim), [1]),
  expectEq("fromArray", "when many items => Some", () => Option.map(Extras__NonEmptyArray.fromArray([
    1,
    2,
    3
  ]), prim => prim), [
    1,
    2,
    3
  ]),
  expectEq("map", "", () => Extras__NonEmptyArray.map(Array.of(1, 2, 3), i => (i << 1)), [
    2,
    4,
    6
  ]),
  expectEq("head", "returns first item", () => Extras__NonEmptyArray.head(Array.of(1, 2, 3)), 1),
  expectEq("last", "returns last item", () => Extras__NonEmptyArray.last(Array.of(1, 2, 3)), 3),
  expectEq("reduce", "when one item, return it", () => Extras__NonEmptyArray.reduce(Array.of(1), add), 1),
  expectEq("reduce", "when two items, return sum", () => Extras__NonEmptyArray.reduce(Array.of(1, 2), add), 3),
  expectEq("reduce", "when many items, return sum", () => Extras__NonEmptyArray.reduce(Array.of(1, 2, 3), add), 6),
  expectEq("maxBy", "return max", () => Extras__NonEmptyArray.maxBy(Array.of(1, 2, 3), Primitive_int.compare), 3),
  expectEq("minBy", "return min", () => Extras__NonEmptyArray.minBy(Array.of(1, 2, 3), Primitive_int.compare), 1),
  expectEq("concat", "", () => Extras__NonEmptyArray.concat(Array.of(1, 2, 3), Array.of(1, 2, 3)), [
    1,
    2,
    3,
    1,
    2,
    3
  ]),
  expectEq("of1", "", () => Array.of(4), [4]),
  expectEq("of2", "", () => Array.of(1, 2), [
    1,
    2
  ]),
  expectEq("of3", "", () => Array.of(1, 2, 3), [
    1,
    2,
    3
  ]),
  expectEq("ofMany", "", () => Array.of(1, 2, 3, 4, 5), [
    1,
    2,
    3,
    4,
    5
  ])
];

let NEA;

let O;

export {
  NEA,
  O,
  expectEq,
  add,
  tests,
}
/* tests Not a pure module */
