// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__Array from "../src/Extras__Array.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";

function test(title, expect, a, b) {
  return Extras__Test.fromPredicate("Array", title, expect, () => {
    let m = a();
    if (Primitive_object.notequal(m, b)) {
      console.log("");
      console.log("== NOT EQUAL : " + title + " ==");
      console.log("a: ", m);
      console.log("b: ", b);
    }
    return Primitive_object.equal(m, b);
  });
}

let unfoldTests = [
  [
    "multiplicative",
    1,
    i => {
      if (i < 100) {
        return [
          i,
          (i << 1)
        ];
      }
      
    },
    [
      1,
      2,
      4,
      8,
      16,
      32,
      64
    ]
  ],
  [
    "multiplicative",
    28,
    i => {
      if (i < 100) {
        return [
          i,
          (i << 1)
        ];
      }
      
    },
    [
      28,
      56
    ]
  ],
  [
    "multiplicative",
    101,
    i => {
      if (i < 100) {
        return [
          i,
          (i << 1)
        ];
      }
      
    },
    []
  ],
  [
    "simple range up",
    5,
    i => {
      if (i <= 20) {
        return [
          i,
          i + 5 | 0
        ];
      }
      
    },
    [
      5,
      10,
      15,
      20
    ]
  ],
  [
    "simple range down",
    20,
    i => {
      if (i > 15) {
        return [
          i,
          i - 1 | 0
        ];
      }
      
    },
    [
      20,
      19,
      18,
      17,
      16
    ]
  ]
].map(param => {
  let expectation = param[0];
  let seed = param[1];
  let generator = param[2];
  let expected = param[3];
  return Extras__Test.fromPredicate("Array", "unfold", expectation, () => Primitive_object.equal(Extras__Array.unfold(seed, generator), expected));
});

let tests = [
  test("of1", "wrap item in an array", () => Array.of(1), [1]),
  test("of1", "wrap array in array", () => Array.of([
    1,
    2,
    3
  ]), [[
      1,
      2,
      3
    ]]),
  test("of1", "wrap None in array", () => Array.of(undefined), [undefined]),
  test("fromOption", "if None => empty", () => Extras__Array.fromOption(undefined), []),
  test("fromOption", "if Some => array with one item", () => Extras__Array.fromOption(3), [3]),
  test("last", "when empty, return None", () => Extras__Array.last([]), undefined),
  test("last", "when not empty, return Some", () => Extras__Array.last([
    1,
    2,
    3
  ]), 3),
  test("head", "when empty, return None", () => Extras__Array.head([]), undefined),
  test("head", "when not empty, return first", () => Extras__Array.head([1]), 1),
  test("lastIndex", "when more than 1 item, return Some", () => Extras__Array.lastIndex([
    1,
    2,
    3
  ]), 2),
  test("lastIndex", "when one item, return Some", () => Extras__Array.lastIndex([1]), 0),
  test("lastIndex", "when empty, return None", () => Extras__Array.lastIndex([]), undefined),
  test("exactlyOneValue", "when empty => None", () => Extras__Array.exactlyOne([]), undefined),
  test("exactlyOneValue", "when one value => Some", () => Extras__Array.exactlyOne([3]), 3),
  test("exactlyOneValue", "when empty => None", () => Extras__Array.exactlyOne([
    1,
    2
  ]), undefined),
  test("prepend", "concats to the beginning", () => Extras__Array.prepend([
    3,
    4,
    5
  ], [
    1,
    2
  ]), [
    1,
    2,
    3,
    4,
    5
  ]),
  test("filterSome", "when empty => []", () => Extras__Array.filterSome([]), []),
  test("filterSome", "when one Some(x) => [x]", () => Extras__Array.filterSome([3]), [3]),
  test("filterSome", "when one None => []", () => Extras__Array.filterSome([undefined]), []),
  test("filterSome", "keep just the Some values", () => Extras__Array.filterSome([
    undefined,
    1,
    2,
    undefined
  ]), [
    1,
    2
  ])
].concat(unfoldTests);

let T;

let A;

export {
  T,
  A,
  test,
  unfoldTests,
  tests,
}
/* unfoldTests Not a pure module */
