// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Option from "rescript/lib/es6/Option.js";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__Unknown from "../src/Extras__Unknown.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";

let tests = [
  Extras__Test.fromPredicate("Unknown", "isNullOrUndefined", "when null => true", () => Extras__Unknown.isNullOrUndefined(null) === true),
  Extras__Test.fromPredicate("Unknown", "isNullOrUndefined", "when undefined => true", () => Extras__Unknown.isNullOrUndefined(undefined) === true),
  Extras__Test.fromPredicate("Unknown", "isNullOrUndefined", "when a number => false", () => Extras__Unknown.isNullOrUndefined(43) === false),
  Extras__Test.fromPredicate("Unknown", "isNullOrUndefined", "when some letters => false", () => Extras__Unknown.isNullOrUndefined("abc") === false),
  Extras__Test.fromPredicate("Unknown", "getBool", "when property exists => Some", () => Primitive_object.equal(Extras__Unknown.getBool({
    a: true
  }, "a"), true)),
  Extras__Test.fromPredicate("Unknown", "getBool", "when property exists => Some", () => Primitive_object.equal(Extras__Unknown.getBool({
    a: false
  }, "a"), false)),
  Extras__Test.fromPredicate("Unknown", "getBool", "when object is null => None", () => Option.isNone(Extras__Unknown.getBool(null, "a")))
];

let T;

let U;

export {
  T,
  U,
  tests,
}
/* tests Not a pure module */
