// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Option from "rescript/lib/es6/Option.js";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__Option from "../src/Extras__Option.mjs";
import * as Extras__Literal from "../src/Extras__Literal.mjs";

let Seven = Extras__Literal.MakeInt({
  value: 7
});

let Yes = Extras__Literal.MakeString({
  value: "yes",
  trimmed: true,
  caseInsensitive: true
});

let tests = [
  Extras__Test.fromPredicate("Literal", "True", "all", () => {
    if (Extras__Literal.True.value === true && Option.isNone(Extras__Literal.True.parse(35)) && Option.isNone(Extras__Literal.True.parse("abc")) && Option.isNone(Extras__Literal.True.parse(false)) && Extras__Option.isSomeAnd(Extras__Literal.True.parse(true), i => Extras__Literal.True.equals(i, Extras__Literal.True.value)) && Extras__Literal.True.equals(Extras__Literal.True.value, Extras__Literal.True.value) && Extras__Literal.True.isTypeOf(true) && Extras__Literal.True.isTypeOf(false) === false) {
      return Extras__Literal.True.isTypeOf(34) === false;
    } else {
      return false;
    }
  }),
  Extras__Test.fromPredicate("Literal", "Seven", "all", () => {
    if (Seven.value === 7 && Option.isNone(Seven.parse(35)) && Option.isNone(Seven.parse("abc")) && Option.isNone(Seven.parse(false)) && Extras__Option.isSomeAnd(Seven.parse(7), i => Seven.equals(i, Seven.value)) && Seven.equals(Seven.value, Seven.value) && Seven.isTypeOf(7) && Seven.isTypeOf(34) === false) {
      return Seven.isTypeOf(false) === false;
    } else {
      return false;
    }
  }),
  Extras__Test.fromPredicate("Literal", "Yes", "all", () => {
    if (Yes.value === "yes" && Option.isNone(Yes.parse(35)) && Option.isNone(Yes.parse("abc")) && Option.isNone(Yes.parse(false)) && Extras__Option.isSomeAnd(Yes.parse("  YES "), i => Yes.equals(i, Yes.value)) && Extras__Option.isSomeAnd(Yes.parse("  yEs "), i => Yes.equals(i, Yes.value)) && Yes.equals(Yes.value, Yes.value) && Yes.isTypeOf("yes") && Yes.isTypeOf("   yEs") && Yes.isTypeOf(34) === false) {
      return Yes.isTypeOf("no") === false;
    } else {
      return false;
    }
  })
];

let T;

let L;

let Unknown;

let OptionEx;

export {
  T,
  L,
  Unknown,
  OptionEx,
  Seven,
  Yes,
  tests,
}
/* Seven Not a pure module */
