// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__Result from "../src/Extras__Result.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function expectEqual(title, expectation, a, b) {
  return Extras__Test.fromPredicate("Result", title, expectation, () => Primitive_object.equal(a(), b));
}

let fromArray = [
  [
    "when empty, return empty",
    [],
    {
      TAG: "Ok",
      _0: []
    }
  ],
  [
    "when one error, return it",
    [{
        TAG: "Error",
        _0: "a"
      }],
    {
      TAG: "Error",
      _0: "a"
    }
  ],
  [
    "when one ok, return it",
    [{
        TAG: "Ok",
        _0: 1
      }],
    {
      TAG: "Ok",
      _0: [1]
    }
  ],
  [
    "when all ok, return all",
    [
      {
        TAG: "Ok",
        _0: 1
      },
      {
        TAG: "Ok",
        _0: 2
      },
      {
        TAG: "Ok",
        _0: 3
      }
    ],
    {
      TAG: "Ok",
      _0: [
        1,
        2,
        3
      ]
    }
  ],
  [
    "when all error, return first",
    [
      {
        TAG: "Error",
        _0: "a"
      },
      {
        TAG: "Error",
        _0: "b"
      },
      {
        TAG: "Error",
        _0: "c"
      }
    ],
    {
      TAG: "Error",
      _0: "a"
    }
  ],
  [
    "when mix, return first error",
    [
      {
        TAG: "Ok",
        _0: 1
      },
      {
        TAG: "Error",
        _0: "a"
      },
      {
        TAG: "Ok",
        _0: 2
      },
      {
        TAG: "Error",
        _0: "b"
      }
    ],
    {
      TAG: "Error",
      _0: "a"
    }
  ]
].map(param => {
  let input = param[1];
  return expectEqual("fromArray", param[0], () => Extras__Result.fromArray(input), param[2]);
});

function mapper(n) {
  if (n < 10) {
    return {
      TAG: "Ok",
      _0: (n << 1)
    };
  } else {
    return {
      TAG: "Error",
      _0: n.toString()
    };
  }
}

let fromArrayMap = [
  [
    "when empty, return empty",
    [],
    {
      TAG: "Ok",
      _0: []
    }
  ],
  [
    "when one error, return it",
    [30],
    {
      TAG: "Error",
      _0: "30"
    }
  ],
  [
    "when one ok, return it",
    [2],
    {
      TAG: "Ok",
      _0: [4]
    }
  ],
  [
    "when all ok, return all",
    [
      1,
      2,
      3
    ],
    {
      TAG: "Ok",
      _0: [
        2,
        4,
        6
      ]
    }
  ],
  [
    "when all error, return first",
    [
      20,
      30,
      40
    ],
    {
      TAG: "Error",
      _0: "20"
    }
  ],
  [
    "when mix, return first error",
    [
      1,
      2,
      14,
      3,
      4
    ],
    {
      TAG: "Error",
      _0: "14"
    }
  ]
].map(param => {
  let input = param[1];
  return expectEqual("fromArrayMap", param[0], () => Extras__Result.fromArrayMap(input, mapper), param[2]);
});

let mapError = [
  [
    "when Error, map the error",
    {
      TAG: "Error",
      _0: 3
    },
    {
      TAG: "Error",
      _0: 6
    }
  ],
  [
    "when Ok, return Ok",
    {
      TAG: "Ok",
      _0: "a"
    },
    {
      TAG: "Ok",
      _0: "a"
    }
  ]
].map(param => {
  let input = param[1];
  return expectEqual("mapError", param[0], () => Extras__Result.mapError(input, i => (i << 1)), param[2]);
});

let fromTryCatch = [
  Extras__Test.fromPredicate("Result", "fromTryCatch", "when throw, return as Error", () => {
    let r = Extras__Result.fromTryCatch(() => Exn.raiseError("banana"));
    if (r.TAG === "Ok") {
      return false;
    }
    let err = Exn.asJsExn(r._0);
    if (err !== undefined) {
      return Primitive_object.equal(Primitive_option.valFromOption(err).message, "banana");
    } else {
      return false;
    }
  }),
  Extras__Test.fromPredicate("Result", "fromTryCatch", "when not throw, return result as Ok", () => Primitive_object.equal(Extras__Result.fromTryCatch(() => 3), {
    TAG: "Ok",
    _0: 3
  }))
];

let toOption = [
  expectEqual("toOption", "when Ok, return Some", () => Extras__Result.toOption({
    TAG: "Ok",
    _0: 4
  }), 4),
  expectEqual("toOption", "when Error, return None", () => Extras__Result.toOption({
    TAG: "Error",
    _0: 4
  }), undefined)
];

let getError = [
  expectEqual("getError", "when Ok, return None", () => Extras__Result.getError({
    TAG: "Ok",
    _0: 4
  }), undefined),
  expectEqual("getError", "when Error, return Some", () => Extras__Result.getError({
    TAG: "Error",
    _0: 4
  }), 4)
];

let allTests = [
  toOption,
  getError,
  fromTryCatch,
  fromArray,
  fromArrayMap,
  mapError
].flat();

let T;

let R;

export {
  T,
  R,
  expectEqual,
  fromArray,
  fromArrayMap,
  mapError,
  fromTryCatch,
  toOption,
  getError,
  allTests,
}
/* fromArray Not a pure module */
