// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Extras__Task from "../src/Extras__Task.mjs";
import * as Extras__Test from "../src/Extras__Test.mjs";
import * as Extras__CmpTests from "./Extras__CmpTests.mjs";
import * as Extras__TaskTest from "./Extras__TaskTest.mjs";
import * as Extras__ArrayTests from "./Extras__ArrayTests.mjs";
import * as Extras__UnionTests from "./Extras__UnionTests.mjs";
import * as Extras__OptionTests from "./Extras__OptionTests.mjs";
import * as Extras__ResultTests from "./Extras__ResultTests.mjs";
import * as Extras__LiteralTests from "./Extras__LiteralTests.mjs";
import * as Extras__PatternTests from "./Extras__PatternTests.mjs";
import * as Extras__UnknownTests from "./Extras__UnknownTests.mjs";
import * as Extras__TrampolineTests from "./Extras__TrampolineTests.mjs";
import * as Extras__NonEmptyArrayTests from "./Extras__NonEmptyArrayTests.mjs";

function isLocalDevelopment() {
  try {
    return (process.env.NODE_ENV === "development");
  } catch (exn) {
    return false;
  }
}

function filter(test) {
  return [""].every(word => Extras__Test.hasKeyword(test, word));
}

let throwOnFailure = !isLocalDevelopment();

let tests = [
  Extras__CmpTests.tests,
  Extras__ArrayTests.tests,
  Extras__OptionTests.tests,
  Extras__ResultTests.allTests,
  Extras__TaskTest.tests,
  Extras__NonEmptyArrayTests.tests,
  Extras__LiteralTests.tests,
  Extras__UnionTests.tests,
  Extras__PatternTests.tests,
  Extras__UnknownTests.tests,
  Extras__TrampolineTests.tests
].flat();

Extras__Task.toPromise(Extras__Task.forEach(Extras__Task.Result.make(() => Extras__Test.runSuite(filter, false, tests), e => e), s => {
  if (s.TAG !== "Ok") {
    if (throwOnFailure) {
      return Exn.raiseError("Could not complete the test suite.");
    } else {
      return;
    }
  }
  if (!throwOnFailure) {
    return;
  }
  let s$1 = s._0;
  if (s$1.fail > 0) {
    return Exn.raiseError("Tests failed: " + s$1.fail.toString());
  }
  
}));

let Test;

let Task;

let Ex;

let onlyShowFailures = false;

export {
  Test,
  Task,
  Ex,
  isLocalDevelopment,
  onlyShowFailures,
  filter,
  throwOnFailure,
  tests,
}
/* throwOnFailure Not a pure module */
