// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/Belt_Option.js";
import * as Extras__Unknown from "./Extras__Unknown.mjs";
import * as Primitive_object from "rescript/lib/es6/Primitive_object.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function MakeOption(P) {
  let isTypeOf = v => {
    if (Extras__Unknown.isUndefined(v)) {
      return true;
    } else {
      return P.isTypeOf(v);
    }
  };
  let equals = (a, b) => Belt_Option.eq(a, b, P.equals);
  return {
    isTypeOf: isTypeOf,
    equals: equals
  };
}

function MakeNullable(P) {
  let isTypeOf = v => {
    if (Extras__Unknown.isNullOrUndefined(v)) {
      return true;
    } else {
      return P.isTypeOf(v);
    }
  };
  let equals = (a, b) => {
    if (Extras__Unknown.isNull(a)) {
      return Extras__Unknown.isNull(b);
    } else if (Extras__Unknown.isUndefined(a)) {
      return Extras__Unknown.isUndefined(b);
    } else if (Extras__Unknown.isNullOrUndefined(b)) {
      return false;
    } else {
      return P.equals(a, b);
    }
  };
  return {
    isTypeOf: isTypeOf,
    equals: equals
  };
}

function MakeNull(P) {
  let isTypeOf = v => {
    if (Extras__Unknown.isNull(v)) {
      return true;
    } else {
      return P.isTypeOf(v);
    }
  };
  let equals = (a, b) => {
    if (Extras__Unknown.isNull(a)) {
      return Extras__Unknown.isNull(b);
    } else if (Extras__Unknown.isNull(b)) {
      return false;
    } else {
      return P.equals(a, b);
    }
  };
  return {
    isTypeOf: isTypeOf,
    equals: equals
  };
}

function MakeTuple2(P) {
  let isTypeOf = u => {
    if (Array.isArray(u) && u.length === 2 && P.A.isTypeOf(u[0])) {
      return P.B.isTypeOf(u[1]);
    } else {
      return false;
    }
  };
  let equals = (param, param$1) => {
    if (P.A.equals(param[0], param$1[0])) {
      return P.B.equals(param[1], param$1[1]);
    } else {
      return false;
    }
  };
  return {
    isTypeOf: isTypeOf,
    equals: equals
  };
}

function MakeTuple3(P) {
  let isTypeOf = u => {
    if (Array.isArray(u) && u.length === 3 && P.A.isTypeOf(u[0]) && P.B.isTypeOf(u[1])) {
      return P.C.isTypeOf(u[2]);
    } else {
      return false;
    }
  };
  let equals = (param, param$1) => {
    if (P.A.equals(param[0], param$1[0]) && P.B.equals(param[1], param$1[1])) {
      return P.C.equals(param[2], param$1[2]);
    } else {
      return false;
    }
  };
  return {
    isTypeOf: isTypeOf,
    equals: equals
  };
}

function MakeTools(P) {
  let make = x => {
    if (P.isTypeOf(x)) {
      return Primitive_option.some(x);
    }
    
  };
  let eq = (x, y) => Belt_Option.flatMap(make(x), x => Belt_Option.map(make(y), y => P.equals(x, y)));
  return {
    make: make,
    eq: eq
  };
}

function isTypeOf(u) {
  return typeof u === "number";
}

function equals(x, y) {
  return x === y;
}

let Int = {
  isTypeOf: isTypeOf,
  equals: equals
};

function isTypeOf$1(u) {
  return typeof u === "number";
}

function equals$1(x, y) {
  return x === y;
}

let Float = {
  isTypeOf: isTypeOf$1,
  equals: equals$1
};

function isTypeOf$2(u) {
  return typeof u === "boolean";
}

function equals$2(x, y) {
  return x === y;
}

let Bool = {
  isTypeOf: isTypeOf$2,
  equals: equals$2
};

function isTypeOf$3(u) {
  return typeof u === "string";
}

function equals$3(x, y) {
  return x.localeCompare(y) === 0.0;
}

let $$String = {
  isTypeOf: isTypeOf$3,
  equals: equals$3
};

let isTypeOf$4 = (function (a) { return (!isNaN(a) && (a instanceof Date) && (typeof a.getMonth === 'function')) });

let equals$4 = Primitive_object.equal;

let $$Date = {
  isTypeOf: isTypeOf$4,
  equals: equals$4
};

export {
  MakeOption,
  MakeNullable,
  MakeNull,
  MakeTuple2,
  MakeTuple3,
  MakeTools,
  Int,
  Float,
  Bool,
  $$String,
  $$Date,
}
/* No side effect */
