// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

let isNull = (function (a) { return a === null });

let isUndefined = (function (a) { return a === undefined });

let isNullOrUndefined = (function (a) { return a === null || a === undefined });

function classify(value) {
  let match = typeof value;
  if (match === "symbol") {
    return {
      TAG: "Symbol",
      _0: value
    };
  } else if (match === "boolean") {
    return {
      TAG: "Bool",
      _0: value
    };
  } else if (match === "string") {
    return {
      TAG: "String",
      _0: value
    };
  } else if (match === "function") {
    return {
      TAG: "Function",
      _0: value
    };
  } else if (match === "object") {
    if (isNull(value)) {
      return "Null";
    } else {
      return {
        TAG: "Object",
        _0: value
      };
    }
  } else if (match === "undefined") {
    return "Undefined";
  } else if (match === "number") {
    return {
      TAG: "Number",
      _0: value
    };
  } else {
    return {
      TAG: "BigInt",
      _0: value
    };
  }
}

function toObject(i) {
  if (typeof i === "object") {
    return Primitive_option.some(i);
  }
  
}

function toBool(i) {
  if (typeof i === "boolean") {
    return i;
  }
  
}

function toFloat(i) {
  if (typeof i === "number") {
    return i;
  }
  
}

function toBigInt(i) {
  if (typeof i === "bigint") {
    return i;
  }
  
}

function toString(i) {
  if (typeof i === "string") {
    return i;
  }
  
}

function toSymbol(i) {
  if (typeof i === "symbol") {
    return Primitive_option.some(i);
  }
  
}

function toFunction(i) {
  if (typeof i === "function") {
    return Primitive_option.some(i);
  }
  
}

function getObject(o, n) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toObject(o[n]);
  }
}

function getObjectBySymbol(o, s) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toObject(o[s]);
  }
}

function getBool(o, n) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toBool(o[n]);
  }
}

function getBoolBySymbol(o, s) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toBool(o[s]);
  }
}

function getFloat(o, n) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toFloat(o[n]);
  }
}

function getFloatBySymbol(o, s) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toFloat(o[s]);
  }
}

function getBigInt(o, n) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toBigInt(o[n]);
  }
}

function getBigIntBySymbol(o, s) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toBigInt(o[s]);
  }
}

function getString(o, n) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toString(o[n]);
  }
}

function getStringBySymbol(o, s) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toString(o[s]);
  }
}

function getSymbol(o, n) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toSymbol(o[n]);
  }
}

function getSymbolBySymbol(o, s) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toSymbol(o[s]);
  }
}

function getFunction(o, n) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toFunction(o[n]);
  }
}

function getFunctionBySymbol(o, s) {
  if (isNullOrUndefined(o)) {
    return;
  } else {
    return toFunction(o[s]);
  }
}

export {
  classify,
  isUndefined,
  isNull,
  isNullOrUndefined,
  toObject,
  toBool,
  toFloat,
  toBigInt,
  toString,
  toSymbol,
  toFunction,
  getObject,
  getObjectBySymbol,
  getBool,
  getBoolBySymbol,
  getFloat,
  getFloatBySymbol,
  getBigInt,
  getBigIntBySymbol,
  getString,
  getStringBySymbol,
  getSymbol,
  getSymbolBySymbol,
  getFunction,
  getFunctionBySymbol,
}
/* No side effect */
