// Generated by ReScript, PLEASE EDIT WITH CARE


function $$eval(t, x, y) {
  return t(x, y);
}

function fromIntResult(cmp, x, y) {
  return cmp(x, y);
}

function fromMap(f, t, x, y) {
  return t(f(x), f(y));
}

function reverse(t, x, y) {
  return t(y, x);
}

function eq(t, x, y) {
  return t(x, y) === 0.0;
}

function neq(t, x, y) {
  return t(x, y) !== 0.0;
}

function lt(t, x, y) {
  return t(x, y) < 0.0;
}

function lte(t, x, y) {
  return t(x, y) <= 0.0;
}

function gt(t, x, y) {
  return t(x, y) > 0.0;
}

function gte(t, x, y) {
  return t(x, y) >= 0.0;
}

function min(t, x, y) {
  if (lte(t, x, y)) {
    return x;
  } else {
    return y;
  }
}

function max(t, x, y) {
  if (lte(t, x, y)) {
    return y;
  } else {
    return x;
  }
}

function bool(a, b) {
  if (a < b) {
    return -1.0;
  } else if (a > b) {
    return 1.0;
  } else {
    return 0.0;
  }
}

export {
  $$eval,
  fromIntResult,
  fromMap,
  reverse,
  eq,
  neq,
  lt,
  lte,
  gt,
  gte,
  min,
  max,
  bool,
}
/* No side effect */
