// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function fromOption(opt) {
  if (opt !== undefined) {
    return Array.of(Primitive_option.valFromOption(opt));
  } else {
    return [];
  }
}

function isEmpty(xs) {
  return xs.length === 0;
}

function isNotEmpty(xs) {
  return xs.length > 0;
}

function exactlyOne(xs) {
  let match = xs.length;
  if (match !== 1) {
    return;
  } else {
    return Primitive_option.some(xs[0]);
  }
}

function head(xs) {
  return xs[0];
}

function last(xs) {
  if (xs.length === 0) {
    return;
  } else {
    return xs[xs.length - 1 | 0];
  }
}

function lastIndex(xs) {
  let i = xs.length;
  if (i === 0) {
    return;
  } else {
    return i - 1 | 0;
  }
}

function prepend(a, b) {
  return b.concat(a);
}

function filterSome(xs) {
  let f = (value, param) => value;
  let result = [];
  for (let i = 0, i_finish = xs.length; i < i_finish; ++i) {
    let item = xs[i];
    let i$1 = f(item, i);
    if (i$1 !== undefined) {
      result.push(Primitive_option.valFromOption(i$1));
    }
    
  }
  return result;
}

function unfold(state, generator) {
  let result = [];
  let state$1 = state;
  let $$break = false;
  while (!$$break) {
    let match = generator(state$1);
    if (match !== undefined) {
      result.push(match[0]);
      state$1 = match[1];
    } else {
      $$break = true;
    }
  };
  return result;
}

export {
  fromOption,
  isEmpty,
  isNotEmpty,
  exactlyOne,
  head,
  last,
  lastIndex,
  prepend,
  filterSome,
  unfold,
}
/* No side effect */
