// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/Array.js";
import * as Option from "rescript/lib/es6/Option.js";
import * as Extras__Cmp from "./Extras__Cmp.mjs";

function fromArray(xs) {
  let match = xs.length;
  if (match !== 0) {
    return xs;
  }
  
}

function fromArrayExn(xs) {
  return Option.getExn(fromArray(xs), undefined);
}

function map(xs, f) {
  return xs.map(f);
}

function mapi(xs, f) {
  return xs.map(f);
}

function head(xs) {
  return xs[0];
}

function last(xs) {
  return xs[xs.length - 1 | 0];
}

function reduce(xs, f) {
  return $$Array.reduceWithIndex(xs, head(xs), (sum, val, inx) => {
    if (inx === 0) {
      return sum;
    } else {
      return f(sum, val);
    }
  });
}

function minBy(xs, cmp) {
  return reduce(xs, (i, j) => Extras__Cmp.min(cmp, i, j));
}

function maxBy(xs, cmp) {
  return reduce(xs, (i, j) => Extras__Cmp.max(cmp, i, j));
}

function concat(a, b) {
  return a.concat(b);
}

function concatArray(a, b) {
  return a.concat(b);
}

let Cmp;

export {
  Cmp,
  fromArray,
  fromArrayExn,
  map,
  mapi,
  head,
  last,
  reduce,
  maxBy,
  minBy,
  concat,
  concatArray,
}
/* No side effect */
