// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Option from "rescript/lib/es6/Option.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function work(f) {
  return {
    TAG: "Work",
    _0: f
  };
}

function resolve(n) {
  return {
    TAG: "Done",
    _0: n
  };
}

function solve(t) {
  let state = t;
  let solution;
  while (Option.isNone(solution)) {
    let s = state;
    if (s.TAG === "Done") {
      solution = Primitive_option.some(s._0);
    } else {
      state = s._0();
    }
  };
  return Option.getExn(solution, undefined);
}

export {
  work,
  resolve,
  solve,
}
/* No side effect */
