// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Extras__Cmp from "./Extras__Cmp.mjs";

function MakeEquals(C) {
  let __x = C.cmp;
  let eq = (extra, extra$1) => Extras__Cmp.eq(__x, extra, extra$1);
  let __x$1 = C.cmp;
  let neq = (extra, extra$1) => Extras__Cmp.neq(__x$1, extra, extra$1);
  return {
    eq: eq,
    neq: neq
  };
}

function MakeCompare(C) {
  let __x = C.cmp;
  let lt = (extra, extra$1) => Extras__Cmp.lt(__x, extra, extra$1);
  let __x$1 = C.cmp;
  let lte = (extra, extra$1) => Extras__Cmp.lte(__x$1, extra, extra$1);
  let __x$2 = C.cmp;
  let gt = (extra, extra$1) => Extras__Cmp.gt(__x$2, extra, extra$1);
  let __x$3 = C.cmp;
  let gte = (extra, extra$1) => Extras__Cmp.gte(__x$3, extra, extra$1);
  let __x$4 = C.cmp;
  let min = (extra, extra$1) => Extras__Cmp.min(__x$4, extra, extra$1);
  let __x$5 = C.cmp;
  let max = (extra, extra$1) => Extras__Cmp.max(__x$5, extra, extra$1);
  return {
    lt: lt,
    lte: lte,
    gt: gt,
    gte: gte,
    min: min,
    max: max
  };
}

let Cmp;

export {
  Cmp,
  MakeEquals,
  MakeCompare,
}
/* No side effect */
