// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Option from "rescript/lib/es6/Option.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function isSomeAnd(o, p) {
  if (o !== undefined) {
    return p(Primitive_option.valFromOption(o));
  } else {
    return false;
  }
}

function isNoneOr(o, p) {
  if (o !== undefined) {
    return p(Primitive_option.valFromOption(o));
  } else {
    return true;
  }
}

function toArray(o) {
  return Option.mapOr(o, [], i => [i]);
}

function concat(x, y, f) {
  if (y !== undefined) {
    if (x !== undefined) {
      return Primitive_option.some(f(Primitive_option.valFromOption(x), Primitive_option.valFromOption(y)));
    } else {
      return y;
    }
  } else {
    return x;
  }
}

function fold(x, f, sum) {
  if (x !== undefined) {
    return f(sum, Primitive_option.valFromOption(x));
  } else {
    return sum;
  }
}

function foldBack(sum, f, x) {
  if (x !== undefined) {
    return f(Primitive_option.valFromOption(x), sum);
  } else {
    return sum;
  }
}

function fromOk(r) {
  if (r.TAG === "Ok") {
    return Primitive_option.some(r._0);
  }
  
}

function fromError(r) {
  if (r.TAG === "Ok") {
    return;
  } else {
    return Primitive_option.some(r._0);
  }
}

function fromTryCatch(f) {
  try {
    return Primitive_option.some(f());
  } catch (exn) {
    return;
  }
}

function map2(a, b, m) {
  if (a !== undefined && b !== undefined) {
    return Primitive_option.some(m(Primitive_option.valFromOption(a), Primitive_option.valFromOption(b)));
  }
  
}

function map3(a, b, c, m) {
  if (a !== undefined && b !== undefined && c !== undefined) {
    return Primitive_option.some(m(Primitive_option.valFromOption(a), Primitive_option.valFromOption(b), Primitive_option.valFromOption(c)));
  }
  
}

function map4(a, b, c, d, m) {
  if (a !== undefined && b !== undefined && c !== undefined && d !== undefined) {
    return Primitive_option.some(m(Primitive_option.valFromOption(a), Primitive_option.valFromOption(b), Primitive_option.valFromOption(c), Primitive_option.valFromOption(d)));
  }
  
}

function map5(a, b, c, d, e, m) {
  if (a !== undefined && b !== undefined && c !== undefined && d !== undefined && e !== undefined) {
    return Primitive_option.some(m(Primitive_option.valFromOption(a), Primitive_option.valFromOption(b), Primitive_option.valFromOption(c), Primitive_option.valFromOption(d), Primitive_option.valFromOption(e)));
  }
  
}

function orElseWith(a, b) {
  if (a !== undefined) {
    return a;
  } else {
    return b();
  }
}

function flatten(o) {
  if (o === undefined) {
    return;
  }
  let r = Primitive_option.valFromOption(o);
  if (r !== undefined) {
    return r;
  }
  
}

export {
  isSomeAnd,
  isNoneOr,
  toArray,
  concat,
  fold,
  foldBack,
  fromOk,
  fromError,
  fromTryCatch,
  map2,
  map3,
  map4,
  map5,
  flatten,
  orElseWith,
}
/* No side effect */
