// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Option from "rescript/lib/es6/Option.js";
import * as Extras__Option from "./Extras__Option.mjs";
import * as Extras__Unknown from "./Extras__Unknown.mjs";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function Make(C) {
  let isTypeOf = u => u === C.value;
  let value = C.value;
  let parse = u => {
    if (u === C.value) {
      return Primitive_option.some(value);
    }
    
  };
  let equals = (_x, _y) => true;
  return {
    isTypeOf: isTypeOf,
    parse: parse,
    equals: equals,
    value: value
  };
}

let value = null;

function isTypeOf(u) {
  return u === value;
}

function parse(u) {
  if (u === value) {
    return Primitive_option.some(value);
  }
  
}

function equals(_x, _y) {
  return true;
}

let Null = {
  isTypeOf: isTypeOf,
  parse: parse,
  equals: equals,
  value: value
};

function isTypeOf$1(u) {
  return u === true;
}

function parse$1(u) {
  if (u === true) {
    return Primitive_option.some(true);
  }
  
}

function equals$1(_x, _y) {
  return true;
}

let True = {
  isTypeOf: isTypeOf$1,
  parse: parse$1,
  equals: equals$1,
  value: true
};

function isTypeOf$2(u) {
  return u === false;
}

function parse$2(u) {
  if (u === false) {
    return Primitive_option.some(false);
  }
  
}

function equals$2(_x, _y) {
  return true;
}

let False = {
  isTypeOf: isTypeOf$2,
  parse: parse$2,
  equals: equals$2,
  value: false
};

function MakeInt(C) {
  let value = C.value;
  let isTypeOf = u => u === value;
  let parse = u => {
    if (u === value) {
      return Primitive_option.some(value);
    }
    
  };
  let equals = (_x, _y) => true;
  return {
    isTypeOf: isTypeOf,
    parse: parse,
    equals: equals,
    value: value
  };
}

function MakeString(C) {
  let trim = s => {
    if (C.trimmed) {
      return s.trim();
    } else {
      return s;
    }
  };
  let toLower = s => {
    if (C.caseInsensitive) {
      return s.toLocaleLowerCase();
    } else {
      return s;
    }
  };
  let normalize = s => toLower(trim(s));
  let value = toLower(trim(C.value));
  let isTypeOf = u => Extras__Option.isSomeAnd(Option.map(Extras__Unknown.toString(u), normalize), u => u === value);
  let parse = u => {
    if (isTypeOf(u)) {
      return value;
    }
    
  };
  let equals = (_x, _y) => true;
  return {
    isTypeOf: isTypeOf,
    parse: parse,
    equals: equals,
    value: value
  };
}

export {
  Make,
  MakeInt,
  MakeString,
  Null,
  True,
  False,
}
/* No side effect */
