// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Exn from "rescript/lib/es6/Exn.js";
import * as Option from "rescript/lib/es6/Option.js";
import * as Extras__Option from "./Extras__Option.mjs";
import * as Extras__Pattern from "./Extras__Pattern.mjs";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function Make2(funarg) {
  let A_Tools = Extras__Pattern.MakeTools(funarg.A);
  let B_Tools = Extras__Pattern.MakeTools(funarg.B);
  let make = value => Extras__Option.orElseWith(A_Tools.make(value), () => B_Tools.make(value));
  let matchAB = (value, onA, onB) => {
    let value$1 = Extras__Option.orElseWith(Option.map(A_Tools.make(value), onA), () => Option.map(B_Tools.make(value), onB));
    if (value$1 !== undefined) {
      return Primitive_option.valFromOption(value$1);
    } else {
      return Exn.raiseError("The value was unsafely cast and did not match any of the provided types.");
    }
  };
  let equals = (x, y) => Option.getOr(Extras__Option.orElseWith(A_Tools.eq(x, y), () => B_Tools.eq(x, y)), false);
  return {
    toA: A_Tools.make,
    toB: B_Tools.make,
    make: make,
    matchAB: matchAB,
    equals: equals
  };
}

function Make3(funarg) {
  let A_Tools = Extras__Pattern.MakeTools(funarg.A);
  let B_Tools = Extras__Pattern.MakeTools(funarg.B);
  let C_Tools = Extras__Pattern.MakeTools(funarg.C);
  let make = value => Extras__Option.orElseWith(Extras__Option.orElseWith(A_Tools.make(value), () => B_Tools.make(value)), () => C_Tools.make(value));
  let matchABC = (value, onA, onB, onC) => {
    let value$1 = Extras__Option.orElseWith(Extras__Option.orElseWith(Option.map(A_Tools.make(value), onA), () => Option.map(B_Tools.make(value), onB)), () => Option.map(C_Tools.make(value), onC));
    if (value$1 !== undefined) {
      return Primitive_option.valFromOption(value$1);
    } else {
      return Exn.raiseError("The value was unsafely cast and did not match any of the provided types.");
    }
  };
  let equals = (x, y) => Option.getOr(Extras__Option.orElseWith(Extras__Option.orElseWith(A_Tools.eq(x, y), () => B_Tools.eq(x, y)), () => C_Tools.eq(x, y)), false);
  return {
    toA: A_Tools.make,
    toB: B_Tools.make,
    toC: C_Tools.make,
    make: make,
    matchABC: matchABC,
    equals: equals
  };
}

function Make4(funarg) {
  let A_Tools = Extras__Pattern.MakeTools(funarg.A);
  let B_Tools = Extras__Pattern.MakeTools(funarg.B);
  let C_Tools = Extras__Pattern.MakeTools(funarg.C);
  let D_Tools = Extras__Pattern.MakeTools(funarg.D);
  let make = value => Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(A_Tools.make(value), () => B_Tools.make(value)), () => C_Tools.make(value)), () => D_Tools.make(value));
  let matchABCD = (value, onA, onB, onC, onD) => {
    let value$1 = Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(Option.map(A_Tools.make(value), onA), () => Option.map(B_Tools.make(value), onB)), () => Option.map(C_Tools.make(value), onC)), () => Option.map(D_Tools.make(value), onD));
    if (value$1 !== undefined) {
      return Primitive_option.valFromOption(value$1);
    } else {
      return Exn.raiseError("The value was unsafely cast and did not match any of the provided types.");
    }
  };
  let equals = (x, y) => Option.getOr(Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(A_Tools.eq(x, y), () => B_Tools.eq(x, y)), () => C_Tools.eq(x, y)), () => D_Tools.eq(x, y)), false);
  return {
    toA: A_Tools.make,
    toB: B_Tools.make,
    toC: C_Tools.make,
    toD: D_Tools.make,
    make: make,
    matchABCD: matchABCD,
    equals: equals
  };
}

function Make5(funarg) {
  let A_Tools = Extras__Pattern.MakeTools(funarg.A);
  let B_Tools = Extras__Pattern.MakeTools(funarg.B);
  let C_Tools = Extras__Pattern.MakeTools(funarg.C);
  let D_Tools = Extras__Pattern.MakeTools(funarg.D);
  let E_Tools = Extras__Pattern.MakeTools(funarg.E);
  let make = value => Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(A_Tools.make(value), () => B_Tools.make(value)), () => C_Tools.make(value)), () => D_Tools.make(value)), () => E_Tools.make(value));
  let matchABCDE = (value, onA, onB, onC, onD, onE) => {
    let value$1 = Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(Option.map(A_Tools.make(value), onA), () => Option.map(B_Tools.make(value), onB)), () => Option.map(C_Tools.make(value), onC)), () => Option.map(D_Tools.make(value), onD)), () => Option.map(E_Tools.make(value), onE));
    if (value$1 !== undefined) {
      return Primitive_option.valFromOption(value$1);
    } else {
      return Exn.raiseError("The value was unsafely cast and did not match any of the provided types.");
    }
  };
  let equals = (x, y) => Option.getOr(Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(Extras__Option.orElseWith(A_Tools.eq(x, y), () => B_Tools.eq(x, y)), () => C_Tools.eq(x, y)), () => D_Tools.eq(x, y)), () => E_Tools.eq(x, y)), false);
  return {
    toA: A_Tools.make,
    toB: B_Tools.make,
    toC: C_Tools.make,
    toD: D_Tools.make,
    toE: E_Tools.make,
    make: make,
    matchABCDE: matchABCDE,
    equals: equals
  };
}

export {
  Make2,
  Make3,
  Make4,
  Make5,
}
/* No side effect */
