// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Result from "rescript/lib/es6/Result.js";
import * as $$Promise from "rescript/lib/es6/Promise.js";
import * as Extras__Result from "./Extras__Result.mjs";

function make(promise, onError) {
  return () => $$Promise.$$catch(promise(), e => Promise.resolve(onError(e)));
}

function map(t, f) {
  return () => t().then(r => Promise.resolve(f(r)));
}

function toPromise(t) {
  return t();
}

let forEach = map;

function spy(t, effect) {
  return () => t().then(r => {
    effect(r);
    return Promise.resolve(r);
  });
}

function make$1(promise, onError) {
  return make(() => promise().then(ok => Promise.resolve({
    TAG: "Ok",
    _0: ok
  })), e => ({
    TAG: "Error",
    _0: onError(e)
  }));
}

function mapError(t, f) {
  return map(t, __x => Extras__Result.mapError(__x, f));
}

function mapOk(t, f) {
  return map(t, __x => Result.map(__x, f));
}

function flatMap(t, f) {
  return map(t, __x => Result.flatMap(__x, f));
}

function toOption(t) {
  return map(t, Extras__Result.toOption);
}

let Result$1 = {
  make: make$1,
  mapError: mapError,
  mapOk: mapOk,
  flatMap: flatMap,
  toOption: toOption
};

export {
  make,
  map,
  toPromise,
  forEach,
  spy,
  Result$1 as Result,
}
/* No side effect */
